# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import api_pb2 as api__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegistrationStub:
    """Wire-compatible subset of Kubernetes v1.31's Device Plugin API.  The
    upstream proto uses gogoprotobuf code-generation annotations; those do not
    affect the wire and are intentionally omitted from the Python binding.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/v1beta1.Registration/Register',
                request_serializer=api__pb2.RegisterRequest.SerializeToString,
                response_deserializer=api__pb2.Empty.FromString,
                _registered_method=True)


class RegistrationServicer:
    """Wire-compatible subset of Kubernetes v1.31's Device Plugin API.  The
    upstream proto uses gogoprotobuf code-generation annotations; those do not
    affect the wire and are intentionally omitted from the Python binding.

    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistrationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=api__pb2.RegisterRequest.FromString,
                    response_serializer=api__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1beta1.Registration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1beta1.Registration', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Registration:
    """Wire-compatible subset of Kubernetes v1.31's Device Plugin API.  The
    upstream proto uses gogoprotobuf code-generation annotations; those do not
    affect the wire and are intentionally omitted from the Python binding.

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1beta1.Registration/Register',
            api__pb2.RegisterRequest.SerializeToString,
            api__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DevicePluginStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDevicePluginOptions = channel.unary_unary(
                '/v1beta1.DevicePlugin/GetDevicePluginOptions',
                request_serializer=api__pb2.Empty.SerializeToString,
                response_deserializer=api__pb2.DevicePluginOptions.FromString,
                _registered_method=True)
        self.ListAndWatch = channel.unary_stream(
                '/v1beta1.DevicePlugin/ListAndWatch',
                request_serializer=api__pb2.Empty.SerializeToString,
                response_deserializer=api__pb2.ListAndWatchResponse.FromString,
                _registered_method=True)
        self.GetPreferredAllocation = channel.unary_unary(
                '/v1beta1.DevicePlugin/GetPreferredAllocation',
                request_serializer=api__pb2.PreferredAllocationRequest.SerializeToString,
                response_deserializer=api__pb2.PreferredAllocationResponse.FromString,
                _registered_method=True)
        self.Allocate = channel.unary_unary(
                '/v1beta1.DevicePlugin/Allocate',
                request_serializer=api__pb2.AllocateRequest.SerializeToString,
                response_deserializer=api__pb2.AllocateResponse.FromString,
                _registered_method=True)
        self.PreStartContainer = channel.unary_unary(
                '/v1beta1.DevicePlugin/PreStartContainer',
                request_serializer=api__pb2.PreStartContainerRequest.SerializeToString,
                response_deserializer=api__pb2.PreStartContainerResponse.FromString,
                _registered_method=True)


class DevicePluginServicer:
    """Missing associated documentation comment in .proto file."""

    def GetDevicePluginOptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAndWatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPreferredAllocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Allocate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreStartContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DevicePluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDevicePluginOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevicePluginOptions,
                    request_deserializer=api__pb2.Empty.FromString,
                    response_serializer=api__pb2.DevicePluginOptions.SerializeToString,
            ),
            'ListAndWatch': grpc.unary_stream_rpc_method_handler(
                    servicer.ListAndWatch,
                    request_deserializer=api__pb2.Empty.FromString,
                    response_serializer=api__pb2.ListAndWatchResponse.SerializeToString,
            ),
            'GetPreferredAllocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPreferredAllocation,
                    request_deserializer=api__pb2.PreferredAllocationRequest.FromString,
                    response_serializer=api__pb2.PreferredAllocationResponse.SerializeToString,
            ),
            'Allocate': grpc.unary_unary_rpc_method_handler(
                    servicer.Allocate,
                    request_deserializer=api__pb2.AllocateRequest.FromString,
                    response_serializer=api__pb2.AllocateResponse.SerializeToString,
            ),
            'PreStartContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.PreStartContainer,
                    request_deserializer=api__pb2.PreStartContainerRequest.FromString,
                    response_serializer=api__pb2.PreStartContainerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1beta1.DevicePlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1beta1.DevicePlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DevicePlugin:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDevicePluginOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1beta1.DevicePlugin/GetDevicePluginOptions',
            api__pb2.Empty.SerializeToString,
            api__pb2.DevicePluginOptions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAndWatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/v1beta1.DevicePlugin/ListAndWatch',
            api__pb2.Empty.SerializeToString,
            api__pb2.ListAndWatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPreferredAllocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1beta1.DevicePlugin/GetPreferredAllocation',
            api__pb2.PreferredAllocationRequest.SerializeToString,
            api__pb2.PreferredAllocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Allocate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1beta1.DevicePlugin/Allocate',
            api__pb2.AllocateRequest.SerializeToString,
            api__pb2.AllocateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreStartContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1beta1.DevicePlugin/PreStartContainer',
            api__pb2.PreStartContainerRequest.SerializeToString,
            api__pb2.PreStartContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
